[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_SUPABASE_URL = "https://uwpixmseeqhuknbtghpu.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3cGl4bXNlZXFodWtuYnRnaHB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE1ODkzMzAsImV4cCI6MjA0NzE2NTMzMH0.U3FcYIpgqUVVUyFYzWw8g80Ljcv3O_paS46sVgpiyjs"